# This is a namespace agnostic configuration file for the Franka FR3 robot.
# That is to say, it is not tied to any specific namespace and can be used in
# any namespace. 
# If you require namespace specific configurations, you can easily modify this
# file to include the namespace
# As an example, below you can find:
#
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5
#
# Imagine, you have a specific need to have the lock try count in namespace "NAMESPACE_X"
# to be different than the default value of 5, but leave all the other namespaces as default.
# Add the following lines to the configuration file 
# (or use a different config file, but then you have to mody the launch script to reference that file)
#
# /NAMESPACE_X:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 10
#       lock_sleep_interval: 35
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5


/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98
      enable_overrun: false

      cartesian_elbow_example_controller:
        type: franka_example_controllers/CartesianElbowExampleController

      cartesian_orientation_example_controller:
        type: franka_example_controllers/CartesianOrientationExampleController

      cartesian_pose_elbow_example_controller:
        type: franka_example_controllers/CartesianElbowExampleController

      cartesian_pose_example_controller:
        type: franka_example_controllers/CartesianPoseExampleController

      cartesian_velocity_example_controller:
        type: franka_example_controllers/CartesianVelocityExampleController

      elbow_example_controller:
        type: franka_example_controllers/ElbowExampleController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
        state_interfaces:
          robot_state

      gravity_compensation_example_controller:
        type: franka_example_controllers/GravityCompensationExampleController

      gripper_example_controller:
        type: franka_example_controllers/GripperExampleController

      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController

      joint_impedance_with_ik_example_controller:
        type: franka_example_controllers/JointImpedanceWithIKExampleController

      joint_position_example_controller:
        type: franka_example_controllers/JointPositionExampleController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_velocity_example_controller:
        type: franka_example_controllers/JointVelocityExampleController

      model_example_controller:
        type: franka_example_controllers/ModelExampleController

      move_to_start_example_controller:
        type: franka_example_controllers/MoveToStartExampleController

      twist_broadcaster:
        type: crisp_controllers/TwistBroadcaster

      pose_broadcaster:
        type: crisp_controllers/PoseBroadcaster

      gravity_compensation:
        type: crisp_controllers/CartesianController

      cartesian_impedance_controller:
        type: crisp_controllers/CartesianController

      joint_impedance_controller:
        type: crisp_controllers/CartesianController

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController


/**:
  cartesian_elbow_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_orientation_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_pose_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"   

/**:
  elbow_example_controller:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: true #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: true # return update OK, although lock fails (no update occurs)

/**:
  gravity_compensation_example_controller:
    ros__parameters:
      arm_id: "fr3"
      
/**:
  joint_impedance_example_controller:
    ros__parameters:
      arm_id: "fr3"    
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

/**:
  joint_impedance_with_ik_example_controller:
    ros__parameters:
      arm_id: "fr3"
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

/**:
  joint_position_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  joint_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  joint_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"
 
/**:
  model_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  move_to_start_example_controller:
    ros__parameters:
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

/**:
  twist_broadcaster:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

  pose_broadcaster:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

  gravity_compensation:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      task:
        k_pos_x: 0.0
        k_pos_y: 0.0
        k_pos_z: 0.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 0.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true

  joint_impedance_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      task:
        k_pos_x: 0.0
        k_pos_y: 0.0
        k_pos_z: 0.0
        k_rot_x: 0.0
        k_rot_y: 0.0
        k_rot_z: 0.0

      max_delta_tau: 0.5

      nullspace: 
        stiffness: 5.0
        projector_type: none  # So we are directly controlling the joints!
        damping: 0.5
        max_tau: 5.0
        regularization: 1.0e-06
        weights:
          fr3_joint1.value: 150.0
          fr3_joint2.value: 150.0
          fr3_joint3.value: 150.0
          fr3_joint4.value: 150.0
          fr3_joint5.value: 50.0
          fr3_joint6.value: 30.0
          fr3_joint7.value: 10.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true
      limit_error: true
      limit_torques: true


  cartesian_impedance_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      filter:
        q: 0.5
        dq: 0.5
        output_torque: 0.5

      task:
        k_pos_x: 400.0
        k_pos_y: 400.0
        k_pos_z: 400.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 2.0

      # log:
      #   enabled: true
      #   timing: true

      use_friction: false
      use_coriolis_compensation: true
      use_local_jacobian: true

  torque_feedback_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      
      end_effector_frame: fr3_hand_tcp
      base_frame: base
      
      k_fb: 0.6
      kd: 0.1
      joint_source_topic: target_joint
      torque_threshold: 0.1


  joint_trajectory_controller:
    ros__parameters:
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      gains:
        fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
